// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class CoinsOfTamrielV2
    {
        public static class Activator
        {
            private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IActivatorGetter> DLC2GoldPile03 => Construct(0x182a2);
            public static FormLink<IActivatorGetter> DLC2GoldPile04 => Construct(0x182a3);
            public static FormLink<IActivatorGetter> DLC2GoldPile06 => Construct(0x45c81);
            public static FormLink<IActivatorGetter> DLC2GoldPile05 => Construct(0x45c7f);
        }
    }
}
