// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class CoinsOfTamrielV2
    {
        public static class Flora
        {
            private static FormLink<IFloraGetter> Construct(uint id) => new FormLink<IFloraGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFloraGetter> CoinPurseLargeNordic => Construct(0x275d5);
            public static FormLink<IFloraGetter> CoinPurseSmallDwemer => Construct(0x275d6);
            public static FormLink<IFloraGetter> CoinPurseMediumDwemer => Construct(0x275d7);
            public static FormLink<IFloraGetter> CoinPurseLargeDwemer => Construct(0x275d8);
            public static FormLink<IFloraGetter> CoinPurseSmallNordic => Construct(0x275d3);
            public static FormLink<IFloraGetter> CoinPurseMediumNordic => Construct(0x275d4);
        }
    }
}
