// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class CoinsOfTamrielV2
    {
        public static class LeveledItem
        {
            private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledItemGetter> LootImperialLuckNordic => Construct(0x55e5);
            public static FormLink<ILeveledItemGetter> LootPerkGoldenTouchChangeNordic => Construct(0x55e4);
            public static FormLink<ILeveledItemGetter> LootGoldChangeNordic => Construct(0x55e3);
            public static FormLink<ILeveledItemGetter> LootGoldChange25Nordic => Construct(0x5b4d);
            public static FormLink<ILeveledItemGetter> LootUrnGoldChangeNordic => Construct(0x5b4c);
            public static FormLink<ILeveledItemGetter> LootImperialLuckDwemer => Construct(0x55e8);
            public static FormLink<ILeveledItemGetter> LootPerkGoldenTouchDwemer => Construct(0x55e9);
            public static FormLink<ILeveledItemGetter> LootGoldChangeDwemer => Construct(0x55e7);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldLargeDwemer => Construct(0x275d2);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldMediumDwemer => Construct(0x275d1);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldSmallDwemer => Construct(0x275d0);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldLargeNordic => Construct(0x275cf);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldMediumNordic => Construct(0x275ce);
            public static FormLink<ILeveledItemGetter> CoinPurseGoldSmallNordic => Construct(0x275cd);
            public static FormLink<ILeveledItemGetter> LootGoldChange25DwemerGold => Construct(0x275cc);
            public static FormLink<ILeveledItemGetter> LootGoldChange25DwemerSilver => Construct(0x275cb);
            public static FormLink<ILeveledItemGetter> LootGoldChange25Dwemer => Construct(0x275ca);
            public static FormLink<ILeveledItemGetter> LootGoldChange25NordicGold => Construct(0x275c9);
            public static FormLink<ILeveledItemGetter> LootGoldChange25NordicSilver => Construct(0x275c8);
            public static FormLink<ILeveledItemGetter> LootGoldChange25Silver => Construct(0x40b79);
            public static FormLink<ILeveledItemGetter> LootGoldChange25Gold => Construct(0x40b78);
            public static FormLink<ILeveledItemGetter> LootPerkGoldenTouchNordic => Construct(0x55e6);
            public static FormLink<ILeveledItemGetter> LootFalmerGoldBossDwemer => Construct(0xab0cc);
            public static FormLink<ILeveledItemGetter> LootFalmerCorpseGoldSublistDwemer => Construct(0xab0cb);
        }
    }
}
