// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class CoinsOfTamrielV2
    {
        public static class MiscItem
        {
            private static FormLink<IMiscItemGetter> Construct(uint id) => new FormLink<IMiscItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMiscItemGetter> Alessia003 => Construct(0x54dd);
            public static FormLink<IMiscItemGetter> Alessia002 => Construct(0x54dc);
            public static FormLink<IMiscItemGetter> Gold003 => Construct(0xd63);
            public static FormLink<IMiscItemGetter> Gold002 => Construct(0xd62);
            public static FormLink<IMiscItemGetter> Dwemercoin003 => Construct(0x54e0);
            public static FormLink<IMiscItemGetter> Alessia001 => Construct(0x54db);
            public static FormLink<IMiscItemGetter> Dwemercoin002 => Construct(0x54df);
            public static FormLink<IMiscItemGetter> Dwemercoin001 => Construct(0x54de);
        }
    }
}
